id: P27219E1F
initial_creation_type: input
source_metadata:
  Title: Bauddha Tantra Kośa (Part I)
  Editor: Dwivedi, Vajravallabha & Thinlay Ram Shashni
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1990'
  Bauddha tantra kośa (I):
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:35:53.267045'
last_modified_at: '2022-03-08T16:35:53.267058'
